const typographyJson = {
  fontFamily: "Lato",
  totalStyles: 65,
  categories: {
    display: [
      {
        name: "display/display-xl, 56/semibold",
        fontSize: 56,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PERCENT", value: 120 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "display/display-xl, 56/bold",
        fontSize: 56,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PERCENT", value: 120 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "display/display-lg, 48/semibold",
        fontSize: 48,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PERCENT", value: 120 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "display/display-lg, 48/bold",
        fontSize: 48,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PERCENT", value: 120 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "display/display-md, 40/semibold",
        fontSize: 40,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PERCENT", value: 120 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "display/display-md, 40/bold",
        fontSize: 40,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PERCENT", value: 120 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
    ],
    heading: [
      {
        name: "heading/title-4xl, 32/semibold",
        fontSize: 32,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 40 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-4xl, 32/bold",
        fontSize: 32,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PIXELS", value: 40 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-3xl, 28/semibold",
        fontSize: 28,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 32 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-3xl, 28/bold",
        fontSize: 28,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PIXELS", value: 32 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-2xl, 22/semibold",
        fontSize: 22,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 28 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-2xl, 22/bold",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PIXELS", value: 28 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-xl, 20/semibold",
        fontSize: 20,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 24 },
        letterSpacing: { unit: "PERCENT", value: -1 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-xl, 20/bold",
        fontSize: 20,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PIXELS", value: 24 },
        letterSpacing: { unit: "PERCENT", value: -1 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-lg, 18/semibold",
        fontSize: 18,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 24 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-lg, 18/bold",
        fontSize: 18,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PIXELS", value: 24 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-base, 16/semibold",
        fontSize: 16,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-base, 16/bold",
        fontSize: 16,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-md, 15/semibold",
        fontSize: 15,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-md, 15/bold",
        fontSize: 15,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-sm, 14/semibold",
        fontSize: 14,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-sm, 14/bold",
        fontSize: 14,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-xs, 13/semibold",
        fontSize: 13,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "heading/title-xs, 13/bold",
        fontSize: 13,
        fontWeight: "bold",
        fontStyle: "Heavy",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
    ],
    body: [
      {
        name: "body/text-2xl, 18/regular",
        fontSize: 18,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 28 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-2xl, 18/medium",
        fontSize: 18,
        fontWeight: "medium",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 28 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-2xl, 18/semibold",
        fontSize: 18,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 28 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-xl, 16/regular",
        fontSize: 16,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 24 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-xl, 16/medium",
        fontSize: 16,
        fontWeight: "medium",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 24 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-xl, 16/semibold",
        fontSize: 16,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 24 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-lg, 15/regular",
        fontSize: 15,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 24 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-lg, 15/medium",
        fontSize: 15,
        fontWeight: "medium",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 24 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-lg, 15/semibold",
        fontSize: 15,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 24 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-base, 14/regular",
        fontSize: 14,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-base, 14/medium",
        fontSize: 14,
        fontWeight: "medium",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-base, 14/semibold",
        fontSize: 14,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-md, 13/regular",
        fontSize: 13,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 18 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-md, 13/medium",
        fontSize: 13,
        fontWeight: "medium",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 18 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-md, 13/semibold",
        fontSize: 13,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 18 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-sm, 12/regular",
        fontSize: 12,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-sm, 12/medium",
        fontSize: 12,
        fontWeight: "medium",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-sm, 12/semibold",
        fontSize: 12,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-xs, 11/regular",
        fontSize: 11,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-xs, 11/medium",
        fontSize: 11,
        fontWeight: "medium",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "body/text-xs, 11/semibold",
        fontSize: 11,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
    ],
    label: [
      {
        name: "label/label-lg, 12/regular",
        fontSize: 12,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "label/label-lg, 12/medium",
        fontSize: 12,
        fontWeight: "medium",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "label/label-lg, 12/semibold",
        fontSize: 12,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "label/label-md, 11/regular",
        fontSize: 11,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "label/label-md, 11/medium",
        fontSize: 11,
        fontWeight: "medium",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "label/label-md, 11/semibold",
        fontSize: 11,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "label/label-sm, 10/regular",
        fontSize: 10,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "label/label-sm, 10/medium",
        fontSize: 10,
        fontWeight: "medium",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "label/label-sm, 10/semibold",
        fontSize: 10,
        fontWeight: "semibold",
        fontStyle: "Bold",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
    ],
    link: [
      {
        name: "link/link-xl, 16",
        fontSize: 16,
        fontWeight: "semibold",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "link/link-lg, 15",
        fontSize: 15,
        fontWeight: "semibold",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "link/link-base, 14",
        fontSize: 14,
        fontWeight: "semibold",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "link/link-md, 13",
        fontSize: 13,
        fontWeight: "semibold",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "link/link-sm, 12",
        fontSize: 12,
        fontWeight: "semibold",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
      {
        name: "link/link-xs, 11",
        fontSize: 11,
        fontWeight: "semibold",
        fontStyle: "Semibold",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "NONE",
        textCase: "ORIGINAL",
      },
    ],
    strikethrough: [
      {
        name: "Strikethrough/strike-xl, 14",
        fontSize: 14,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "STRIKETHROUGH",
        textCase: "ORIGINAL",
      },
      {
        name: "Strikethrough/strike-lg, 13",
        fontSize: 13,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 20 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "STRIKETHROUGH",
        textCase: "ORIGINAL",
      },
      {
        name: "Strikethrough/strike-base, 12",
        fontSize: 12,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 16 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "STRIKETHROUGH",
        textCase: "ORIGINAL",
      },
      {
        name: "Strikethrough/strike-md, 11",
        fontSize: 11,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "STRIKETHROUGH",
        textCase: "ORIGINAL",
      },
      {
        name: "Strikethrough/strike-sm, 10",
        fontSize: 10,
        fontWeight: "regular",
        fontStyle: "Regular",
        lineHeight: { unit: "PIXELS", value: 14 },
        letterSpacing: { unit: "PERCENT", value: 0 },
        textDecoration: "STRIKETHROUGH",
        textCase: "ORIGINAL",
      },
    ],
  },
};
export default typographyJson;
